apiVersion: apps/v1
kind: Deployment
metadata:
  name: robot-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: robot
  template:
    metadata:
      labels:
        app: robot
    spec:
      containers:
      - name: robot
        image: us-central1-docker.pkg.dev/cloud-based-robot-management/robot-repo/robot-service:latest
        ports:
        - containerPort: 8080